name: Build Native Bypass

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout main repository
      uses: actions/checkout@v4

    - name: Download Prebuilt Dobby
      run: |
        mkdir -p dobby_prebuilt
        curl -L "https://github.com/thedangcoder/Dobby/releases/download/latest/dobby-android-all.tar.gz" -o dobby.tar.gz
        tar -xzf dobby.tar.gz -C dobby_prebuilt
        echo "[+] Prebuilt Dobby successfully downloaded and extracted!"

    - name: Configure CMake
      run: |
        rm -rf build
        mkdir build
        cd build
        cmake .. \
          -DCMAKE_TOOLCHAIN_FILE=$ANDROID_NDK_LATEST_HOME/build/cmake/android.toolchain.cmake \
          -DANDROID_ABI=x86_64 \
          -DANDROID_PLATFORM=android-24 \
          -DCMAKE_BUILD_TYPE=Release

    - name: Build Library
      run: |
        cd build
        make

    - name: Upload Compiled Library
      uses: actions/upload-artifact@v4
      with:
        name: liboxide_bypass-arm64
        path: build/liboxide_bypass.so
